package com.prodnees.core.domain.doc;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.prodnees.core.config.constants.DateTimeFormats;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Transient;
import java.time.LocalDateTime;

/**
 * A document that can be referenced in other Objects or ApprovalDocument
 * <P>{@link com.prodnees.core.domain.batch.BatchApprovalDocument}</P>
 * <P>{@link com.prodnees.core.domain.stage.StageApprovalDocument}</P>
 */
@Entity
public class NeesDoc {

    public String getDocNumber() {
        return docNumber;
    }

    public NeesDoc setDocNumber(String docNumber) {
        this.docNumber = docNumber;
        return this;
    }

    public interface Columns {

    }

    @Id
    @GeneratedValue
    private int id;

    //Unique AlphaNumeric number generated by the System
    private String docNumber;

    //File name but can be edited later
    private String name;

    private String description;

    //Files will not be permanently deleted. Will not be visible to the User if marked as deleted
    private boolean deleted;

    private DocTypeEnum docTypeEnum;
    private DocSubType docSubType;
    private NeesObjectType neesObjectType;
    private Integer objectId;
    private String mimeContentType;
    @JsonFormat(pattern = DateTimeFormats.DATE_TIME)
    private LocalDateTime createdDatetime;
    @Transient()
    private byte[] file;

    public int getId() {
        return id;
    }

    public NeesDoc setId(int id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return name;
    }

    public NeesDoc setName(String name) {
        this.name = name;
        return this;
    }

    public String getDescription() {
        return description;
    }

    public NeesDoc setDescription(String description) {
        this.description = description;
        return this;
    }

    public boolean isDeleted() {
        return deleted;
    }

    public NeesDoc setDeleted(boolean deleted) {
        this.deleted = deleted;
        return this;
    }

    public DocTypeEnum getDocType() {
        return docTypeEnum;
    }

    public NeesDoc setDocType(DocTypeEnum docTypeEnum) {
        this.docTypeEnum = docTypeEnum;
        return this;
    }

    public DocSubType getDocSubType() {
        return docSubType;
    }

    public NeesDoc setDocSubType(DocSubType docSubType) {
        this.docSubType = docSubType;
        return this;
    }

    public NeesObjectType getNeesObjectType() {
        return neesObjectType;
    }

    public NeesDoc setNeesObjectType(NeesObjectType neesObjectType) {
        this.neesObjectType = neesObjectType;
        return this;
    }

    public Integer getObjectId() {
        return objectId;
    }

    public NeesDoc setObjectId(Integer objectId) {
        this.objectId = objectId;
        return this;
    }

    public String getMimeContentType() {
        return mimeContentType;
    }

    public NeesDoc setMimeContentType(String contentType) {
        this.mimeContentType = contentType;
        return this;
    }

    public LocalDateTime getCreatedDatetime() {
        return createdDatetime;
    }

    public NeesDoc setCreatedDatetime(LocalDateTime createdDatetime) {
        this.createdDatetime = createdDatetime;
        return this;
    }

    public byte[] getFile() {
        return file;
    }

    public NeesDoc setFile(byte[] file) {
        this.file = file;
        return this;
    }
}
